apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: i52yga4v8-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:4e87f9a29bb8a098dbc16b609012875cd788f3a4@sha256:7ec763c00e4908304fb18f16d131e59c6ff25696741e4e58a5ba4e468b400199
          name: container-image
